import Head from "next/head";
import { Poppins } from "@next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "./Footer";
import React from "react";

const inter = Poppins({
    subsets: ["latin"],
    weight: "400",
});

type AppLayoutProps = {
    children: React.ReactNode | undefined; // React.ReactNode is a type that allows any React element to be passed as a child
};

const AppLayout = ({ children }: AppLayoutProps) => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <>
                {/* NAVBAR COMPONENT */}
                <Navbar />

                {/*  MAIN COMPONENT HERE... */}
                <main className={`${inter.className} py-10 relative w-screen overflow-hidden z-10`}>
                    {children || "Write your component there..."}
                </main>

                {/* FOOTER COMPONENT */}
                <Footer />

                {/* ELLIPSE COMPONENT */}
                <div className="ellipse1 z-0" />
                <div className="ellipse2 z-0" />
            </>
        </>
    );
};

export default AppLayout;
